# Autogenerated with SMOP version 0.26.2
# main.py apply.m

from __future__ import division
try:
    from runtime import *
except ImportError:
    from smop.runtime import *

def apply_(*args,**kwargs):
    varargin = cellarray(args)
    nargin = 0-[].count(None)+len(args)

    global D
    n=100
    MAX=1000
    fieldnames=[char('u'),char('v'),char('x'),char('y'),char('logL'),char('logWt')]
    f=size_(fieldnames,2)
    cObj=cell_([n,f])
    Obj=cell2struct_(cObj,fieldnames,2)
    cSamples=cell_([MAX,f])
    Samples=cell2struct_(cSamples,fieldnames,2)
    cTry=cell_([1,f])
    Try=cell2struct_(cTry,fieldnames,2)
    D=matlabarray([4.73,0.45,- 1.73,1.09,2.19,0.12,1.31,1.0,1.32,1.07,0.86,- 0.49,- 2.59,1.73,2.11,1.61,4.98,1.71,2.23,- 57.2,0.96,1.25,- 1.56,2.45,1.19,2.17,- 10.66,1.91,- 4.16,1.92,0.1,1.98,- 2.51,5.55,- 0.47,1.91,0.95,- 0.78,- 0.84,1.72,- 0.01,1.48,2.7,1.21,4.41,- 4.79,1.33,0.81,0.2,1.58,1.29,16.19,2.75,- 2.38,- 1.79,6.5,- 18.53,0.72,0.94,3.64,1.94,- 0.11,1.57,0.57])
    return Obj,Samples,Try,n,MAX
